### ISSUE TITLE
dev_omemo: OTR error when receiving a status message

### ISSUE THREAD

**Issue by mimi89999** [zom/Zom-Android-XMPP#203]
**Version:** 15.1.0-alpha-1
**Device:** Samsung Galaxy S4 Mini (serranoltexx)
**Android Version:** Lineage OS 14.1 (Android 7.1.1)

When Zom receives a status message (sent by Conversations), it produces that error in the logcat:
```
04-11 19:21:53.202 E/Zom     (19709): net.java.otr4j.OtrException: OTRv2 is not supported by this session
04-11 19:21:53.202 E/Zom     (19709): 	at net.java.otr4j.session.SessionImpl.startSession(SessionImpl.java:742)
04-11 19:21:53.202 E/Zom     (19709): 	at net.java.otr4j.OtrEngineImpl.startSession(OtrEngineImpl.java:110)
04-11 19:21:53.202 E/Zom     (19709): 	at org.awesomeapp.messenger.crypto.otr.OtrChatManager.startSession(OtrChatManager.java:271)
04-11 19:21:53.202 E/Zom     (19709): 	at org.awesomeapp.messenger.crypto.otr.OtrChatSessionAdapter$1.run(OtrChatSessionAdapter.java:43)
04-11 19:21:53.202 E/Zom     (19709): 	at org.awesomeapp.messenger.util.Debug.wrapExceptions(Debug.java:119)
04-11 19:21:53.202 E/Zom     (19709): 	at org.awesomeapp.messenger.crypto.otr.OtrChatSessionAdapter.startChatEncryption(OtrChatSessionAdapter.java:38)
04-11 19:21:53.202 E/Zom     (19709): 	at org.awesomeapp.messenger.service.adapters.ChatSessionAdapter.presenceChanged(ChatSessionAdapter.java:215)
04-11 19:21:53.202 E/Zom     (19709): 	at org.awesomeapp.messenger.service.adapters.ContactListManagerAdapter$ContactListListenerAdapter.onContactsPresenceUpdate(ContactListManagerAdapter.java:539)
04-11 19:21:53.202 E/Zom     (19709): 	at org.awesomeapp.messenger.model.ContactListManager.notifyContactsPresenceUpdated(ContactListManager.java:520)
04-11 19:21:53.202 E/Zom     (19709): 	at org.awesomeapp.messenger.plugin.xmpp.XmppConnection.handleChatState(XmppConnection.java:3808)
04-11 19:21:53.202 E/Zom     (19709): 	at org.awesomeapp.messenger.plugin.xmpp.XmppConnection.access$1900(XmppConnection.java:183)
04-11 19:21:53.202 E/Zom     (19709): 	at org.awesomeapp.messenger.plugin.xmpp.XmppConnection$6.processStanza(XmppConnection.java:1752)
04-11 19:21:53.202 E/Zom     (19709): 	at org.jivesoftware.smack.AbstractXMPPConnection$4.run(AbstractXMPPConnection.java:1164)
04-11 19:21:53.202 E/Zom     (19709): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
04-11 19:21:53.202 E/Zom     (19709): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-11 19:21:53.202 E/Zom     (19709): 	at java.lang.Thread.run(Thread.java:761)
```

**Comment by mimi89999** [comment]
@n8fr8

**Comment by mimi89999** [comment]
That appears to be fixed.
