### ISSUE TITLE
dev_omemo: otrPolicyAuto always set to true

### ISSUE THREAD

**Issue by mimi89999** [zom/Zom-Android-XMPP#209]
https://github.com/zom/Zom-Android/blob/dev_omemo/app/src/main/java/org/awesomeapp/messenger/ui/ConversationView.java#L289

This causes Zom to always attempt OTR (in some case) and makes it impossible to do OMEMO (in that case).

**Comment by n8fr8** [comment]
Currently, with Zom, we do simultaneous OMEMO and OTR sessions. It does actually work. We do this to allow messages via OMEMO, but media sharing via OTR (since we currently use our OTRDATA feature for this).

Now, we are moving as fast as possible to implement the Conversations.im method of file sharing and encryption, so we don't need to do this simultaneous craziness.

The resolution then may be to work on that implementation, and then disable OTR entirely when OMEMO is possible.

**Comment by mimi89999** [comment]
Hmm... That didn't work for me and Vanitas. We were getting:
`net.java.otr4j.OtrException: OTRv2 is not supported by this session`

**Comment by mimi89999** [comment]
@n8fr8 After every message I sent to @vanitasvitae. He had the same issue. The encryption setting was set to never.
```
04-13 22:56:27.595 30204-30204/im.zom.messenger.debug E/Zom: startSession
                                                             net.java.otr4j.OtrException: OTRv2 is not supported by this session
                                                                 at net.java.otr4j.session.SessionImpl.startSession(SessionImpl.java:742)
                                                                 at net.java.otr4j.OtrEngineImpl.startSession(OtrEngineImpl.java:110)
                                                                 at org.awesomeapp.messenger.crypto.otr.OtrChatManager.startSession(OtrChatManager.java:271)
                                                                 at org.awesomeapp.messenger.crypto.otr.OtrChatSessionAdapter$1.run(OtrChatSessionAdapter.java:43)
                                                                 at org.awesomeapp.messenger.util.Debug.wrapExceptions(Debug.java:119)
                                                                 at org.awesomeapp.messenger.crypto.otr.OtrChatSessionAdapter.startChatEncryption(OtrChatSessionAdapter.java:38)
                                                                 at org.awesomeapp.messenger.ui.ConversationView.setOTRState(ConversationView.java:388)
                                                                 at org.awesomeapp.messenger.ui.ConversationView$1.run(ConversationView.java:313)
                                                                 at android.os.Handler.handleCallback(Handler.java:751)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6126)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by mimi89999** [comment]
@n8fr8 Is OTRDATA documented somewhere?

**Comment by n8fr8** [comment]
Here:
https://dev.guardianproject.info/projects/gibberbot/wiki/OTRDATA_Specifications

It is deprecated however, since we are moving to the Conversations approach to sharing using the XEP for HTTP Upload:
https://xmpp.org/extensions/xep-0363.html

That said, the issue with OTRv2 error you are saying is something that needs to be fixed.

**Comment by mimi89999** [comment]
@n8fr8 Still having the same issue on alpha2. Same error output. Also issue on Zom <---> Zom. Conversations ---> Zom works fine.

**Comment by n8fr8** [comment]
Thanks for the report. I have some new commits coming that should address this.
