### ISSUE TITLE
Error displaying contact if contact doesn't have an OTR fingerprint

### ISSUE THREAD

**Issue by mimi89999** [zom/Zom-Android-XMPP#228]
When I try to display contact info of a contact that doesn't have an OTR fingerprint (one using Conversations/Gajim/[clocc](https://github.com/vanitasvitae/clocc)), I get this error:
```
04-25 18:41:03.937 15116-15116/im.zom.messenger.debug E/Zom: error displaying contact
                                                             java.lang.Exception: Invalid key: null
                                                                 at org.awesomeapp.messenger.ui.ContactDisplayActivity.displayOtrFingerprints(ContactDisplayActivity.java:177)
                                                                 at org.awesomeapp.messenger.ui.ContactDisplayActivity.access$400(ContactDisplayActivity.java:54)
                                                                 at org.awesomeapp.messenger.ui.ContactDisplayActivity$2.onPostExecute(ContactDisplayActivity.java:153)
                                                                 at org.awesomeapp.messenger.ui.ContactDisplayActivity$2.onPostExecute(ContactDisplayActivity.java:127)
                                                                 at android.os.AsyncTask.finish(AsyncTask.java:667)
                                                                 at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                 at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6128)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

Tag: bug

**Comment by mimi89999** [comment]
That issue is fixed. Thanks.
