### ISSUE TITLE
Tor hidden service auth problems: failed certificate verification

### ISSUE THREAD

**Issue by Gaffen** [zom/Zom-Android-XMPP#26]
Due to this it is currently impossible to build contact lists or message contacts whilst using a tor hidden service.

The following error appears in the debug log:

`10-28 17:45:24.892 10469-13425/org.awesomeapp.messenger.debug W/AbstractXMPPConnection: java.security.cert.CertificateException: Hostname verification of certificate failed. Certificate does not authenticate 5rgdtlawqkcplz75.onion
10-28 17:45:24.892 10469-13425/org.awesomeapp.messenger.debug W/AbstractXMPPConnection:     at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(XMPPTCPConnection.java:763)
10-28 17:45:24.892 10469-13425/org.awesomeapp.messenger.debug W/AbstractXMPPConnection:     at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1000(XMPPTCPConnection.java:140)
10-28 17:45:24.892 10469-13425/org.awesomeapp.messenger.debug W/AbstractXMPPConnection:     at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1010)
10-28 17:45:24.892 10469-13425/org.awesomeapp.messenger.debug W/AbstractXMPPConnection:     at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:944)
10-28 17:45:24.892 10469-13425/org.awesomeapp.messenger.debug W/AbstractXMPPConnection:     at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:959)
10-28 17:45:24.892 10469-13425/org.awesomeapp.messenger.debug W/AbstractXMPPConnection:     at java.lang.Thread.run(Thread.java:856)`

**Comment by n8fr8** [comment]
Can you share your public jabber server domain?

Do you have a Root CACert signed certificate?

**Comment by Gaffen** [comment]
Sure, my personal server is w5castv5k4dhwexj.onion, however it's not open to registration at the moment.

It was a while ago I set it up so I can't remember if I made a root signed CACert for the hidden service, however I know I did so for the non-hidden service and would be surprised if I hadn't. I'll try to check later.
