### ISSUE TITLE
Opening a chat with a blocked contact crashes the app

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-Android-XMPP#357]
I tapped on a contact who had blocked me ("Sorry, you are blocked by this user") and once in the profile view I tap the chat icon. The app crashes. 

After the app reloads if I perform the same actions the chat usually opens. 
Reproduced this bug various times.

Device: Moto X, Moto G Play, Galaxy Samsung 7
App version and build: 15.3 RC 1

**Comment by cstiens** [comment]
This is still happening sometimes, but not all the time. I guess it would make most sense to not allow the profile view to be opened for contacts that block/reject your friend request.

**Comment by n8fr8** [comment]
We really need you to get setup with a tool to capture crash log outputs locally. 

You should try to install this tool: https://developer.android.com/studio/profile/monitor.html

**Comment by tiffrobo** [comment]
Ok. I will look into it. Thanks!

**Comment by cstiens** [comment]
Hey @n8fr8 We have android studio installed now and ran debugging on the crash. It's a little hard to find the info you need (still haven't figured out filters), but here's the log for the beginning of the crash that happened after I selected chat from someone's profile:

                                                   --------- beginning of crash
10-17 13:24:51.524 14578-14578/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: im.zom.messenger, PID: 14578
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{im.zom.messenger/org.awesomeapp.messenger.ui.ConversationDetailActivity}: java.lang.IllegalArgumentException: Unknown URL content://org.awesomeapp.messenger.provider.Imps/contacts/-1
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2947)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3008)
                                                       at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6688)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
                                                    Caused by: java.lang.IllegalArgumentException: Unknown URL content://org.awesomeapp.messenger.provider.Imps/contacts/-1
                                                       at org.awesomeapp.messenger.provider.ImpsProvider.queryInternal(ImpsProvider.java:1883)
                                                       at org.awesomeapp.messenger.provider.ImpsProvider.query(ImpsProvider.java:1464)
                                                       at android.content.ContentProvider.query(ContentProvider.java:1027)
                                                       at android.content.ContentProvider$Transport.query(ContentProvider.java:243)
                                                       at android.content.ContentResolver.query(ContentResolver.java:536)
                                                       at android.content.ContentResolver.query(ContentResolver.java:478)
                                                       at org.awesomeapp.messenger.ui.ConversationView.bindChat(ConversationView.java:1471)
                                                       at org.awesomeapp.messenger.ui.ConversationDetailActivity.processIntent(ConversationDetailActivity.java:294)
                                                       at org.awesomeapp.messenger.ui.ConversationDetailActivity.onCreate(ConversationDetailActivity.java:187)
                                                       at android.app.Activity.performCreate(Activity.java:6912)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2900)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3008) 
                                                       at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6688) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
