### ISSUE TITLE
NPE on android pixel

### ISSUE THREAD

**Issue by abeluck** [zom/Zom-Android-XMPP#495]
With the version from the play store, the app crashes after logging in

```
09-19 10:41:34.718 21090 21491 D SMACK   : User logged (0): abel.e66ec567@home.zom.im:80/ChatSecureZom-bef7853b
09-19 10:41:34.719 21090 21491 D ZomXMPP : 0 : authenticated: resumed=true
09-19 10:41:34.721 21090 21491 D SMACK   : XMPPConnection authenticated (XMPPTCPConnection[abel.e66ec567@home.zom.im/ChatSecureZom-bef7853b] (0)) and resumed
09-19 10:41:34.727 21090 21494 W e.smack.AbstractXMPPConnection: Connection XMPPTCPConnection[abel.e66ec567@home.zom.im/ChatSecureZom-bef7853b] (0) closed with error
09-19 10:41:34.728 21090 21494 W e.smack.AbstractXMPPConnection: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
09-19 10:41:34.728 21090 21494 W e.smack.AbstractXMPPConnection: 	at org.jivesoftware.smack.util.XmlStringBuilder.write(XmlStringBuilder.java:570)
09-19 10:41:34.728 21090 21494 W e.smack.AbstractXMPPConnection: 	at org.jivesoftware.smack.util.XmlStringBuilder.write(XmlStringBuilder.java:560)
09-19 10:41:34.728 21090 21494 W e.smack.AbstractXMPPConnection: 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter.writePackets(XMPPTCPConnection.java:1443)
09-19 10:41:34.728 21090 21494 W e.smack.AbstractXMPPConnection: 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter.access$3300(XMPPTCPConnection.java:1257)
09-19 10:41:34.728 21090 21494 W e.smack.AbstractXMPPConnection: 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter$1.run(XMPPTCPConnection.java:1305)
09-19 10:41:34.728 21090 21494 W e.smack.AbstractXMPPConnection: 	at java.lang.Thread.run(Thread.java:764)
09-19 10:41:34.730 21090 21494 E ZomXMPP : 0 : connectionClosedOnError error: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
09-19 10:41:34.730 21090 21494 E ZomXMPP : java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
09-19 10:41:34.730 21090 21494 E ZomXMPP : 	at org.jivesoftware.smack.util.XmlStringBuilder.write(XmlStringBuilder.java:570)
09-19 10:41:34.730 21090 21494 E ZomXMPP : 	at org.jivesoftware.smack.util.XmlStringBuilder.write(XmlStringBuilder.java:560)
09-19 10:41:34.730 21090 21494 E ZomXMPP : 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter.writePackets(XMPPTCPConnection.java:1443)
09-19 10:41:34.730 21090 21494 E ZomXMPP : 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter.access$3300(XMPPTCPConnection.java:1257)
09-19 10:41:34.730 21090 21494 E ZomXMPP : 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter$1.run(XMPPTCPConnection.java:1305)
09-19 10:41:34.730 21090 21494 E ZomXMPP : 	at java.lang.Thread.run(Thread.java:764)
09-19 10:41:34.731 21090 21494 D SMACK   : XMPPConnection closed due to an exception (XMPPTCPConnection[abel.e66ec567@home.zom.im/ChatSecureZom-bef7853b] (0))
09-19 10:41:34.731 21090 21494 D SMACK   : java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
09-19 10:41:34.731 21090 21494 D SMACK   : 	at org.jivesoftware.smack.util.XmlStringBuilder.write(XmlStringBuilder.java:570)
09-19 10:41:34.731 21090 21494 D SMACK   : 	at org.jivesoftware.smack.util.XmlStringBuilder.write(XmlStringBuilder.java:560)
09-19 10:41:34.731 21090 21494 D SMACK   : 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter.writePackets(XMPPTCPConnection.java:1443)
09-19 10:41:34.731 21090 21494 D SMACK   : 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter.access$3300(XMPPTCPConnection.java:1257)
09-19 10:41:34.731 21090 21494 D SMACK   : 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter$1.run(XMPPTCPConnection.java:1305)
09-19 10:41:34.731 21090 21494 D SMACK   : 	at java.lang.Thread.run(Thread.java:764)

```

**Comment by iamironrabbit** [comment]
new build here that should fix this: https://github.com/zom/Zom-Android/releases/tag/15.7.0-RC-3
