### ISSUE TITLE
Crash on ID enter

### ISSUE THREAD

**Issue by licaon-kter** [zom/Zom-Android-XMPP#499]
Huawei custom ROM AOSP 9
15.7.0-RC-2

Skip language, sign it existing, enter valid JID or not, doesn't matter, enter pass, press connect:

```
12-01 20:55:02.303  8797  8797 D [01;31m[KAndroidRuntime[m[K: Shutting down VM
12-01 20:55:02.304  8797  8797 E [01;31m[KAndroidRuntime[m[K: FATAL EXCEPTION: main
12-01 20:55:02.304  8797  8797 E [01;31m[KAndroidRuntime[m[K: Process: im.zom.messenger, PID: 8797
12-01 20:55:02.304  8797  8797 E [01;31m[KAndroidRuntime[m[K: java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.awesomeapp.messenger.ui.onboarding.OnboardingAccount.username' on a null object reference
12-01 20:55:02.304  8797  8797 E [01;31m[KAndroidRuntime[m[K: 	at org.awesomeapp.messenger.ui.onboarding.OnboardingActivity$ExistingAccountTask.onPostExecute(OnboardingActivity.java:825)
12-01 20:55:02.304  8797  8797 E [01;31m[KAndroidRuntime[m[K: 	at org.awesomeapp.messenger.ui.onboarding.OnboardingActivity$ExistingAccountTask.onPostExecute(OnboardingActivity.java:796)
12-01 20:55:02.304  8797  8797 E [01;31m[KAndroidRuntime[m[K: 	at android.os.AsyncTask.finish(AsyncTask.java:695)
12-01 20:55:02.304  8797  8797 E [01;31m[KAndroidRuntime[m[K: 	at android.os.AsyncTask.access$600(AsyncTask.java:180)
12-01 20:55:02.304  8797  8797 E [01;31m[KAndroidRuntime[m[K: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
12-01 20:55:02.304  8797  8797 E [01;31m[KAndroidRuntime[m[K: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-01 20:55:02.304  8797  8797 E [01;31m[KAndroidRuntime[m[K: 	at android.os.Looper.loop(Looper.java:193)
12-01 20:55:02.304  8797  8797 E [01;31m[KAndroidRuntime[m[K: 	at android.app.ActivityThread.main(ActivityThread.java:6680)
12-01 20:55:02.304  8797  8797 E [01;31m[KAndroidRuntime[m[K: 	at java.lang.reflect.Method.invoke(Native Method)
12-01 20:55:02.304  8797  8797 E [01;31m[KAndroidRuntime[m[K: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-01 20:55:02.304  8797  8797 E [01;31m[KAndroidRuntime[m[K: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by iamironrabbit** [comment]
new build here that should fix this: https://github.com/zom/Zom-Android/releases/tag/15.7.0-RC-3

**Comment by licaon-kter** [comment]
Great, it doesn't crash any more.

Albeit it will never connect, https://github.com/zom/Zom-Android/issues/324 :(
