### ISSUE TITLE
Failure to get upload slot on staging server (using Amazon S3)

### ISSUE THREAD

**Issue by abeluck** [zom/Zom-Android-XMPP#501]
1. Use staging.zom.im
2. Use most recent build (15.7.0-RC-3)
3. Send a voice message

Result:

```
01-28 11:14:26.014 11686 16843 I System.out: [socket][9:0] exception java.io.IOException: Success
01-28 11:14:26.039 11686 16843 E ZomXMPP : error getting upload slot
01-28 11:14:26.039 11686 16843 E ZomXMPP : java.io.IOException: Success
01-28 11:14:26.039 11686 16843 E ZomXMPP : 	at java.net.PlainSocketImpl.socksRequestConnection(PlainSocketImpl.java:338)
01-28 11:14:26.039 11686 16843 E ZomXMPP : 	at java.net.PlainSocketImpl.socksConnect(PlainSocketImpl.java:322)
01-28 11:14:26.039 11686 16843 E ZomXMPP : 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:181)
01-28 11:14:26.039 11686 16843 E ZomXMPP : 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
01-28 11:14:26.039 11686 16843 E ZomXMPP : 	at java.net.Socket.connect(Socket.java:901)
01-28 11:14:26.039 11686 16843 E ZomXMPP : 	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
01-28 11:14:26.039 11686 16843 E ZomXMPP : 	at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
01-28 11:14:26.039 11686 16843 E ZomXMPP : 	at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:79)
01-28 11:14:26.039 11686 16843 E ZomXMPP : 	at com.android.okhttp.Connection.connect(Connection.java:143)
01-28 11:14:26.039 11686 16843 E ZomXMPP : 	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
01-28 11:14:26.039 11686 16843 E ZomXMPP : 	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
01-28 11:14:26.039 11686 16843 E ZomXMPP : 	at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:342)
01-28 11:14:26.039 11686 16843 E ZomXMPP : 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:331)
01-28 11:14:26.039 11686 16843 E ZomXMPP : 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:249)
01-28 11:14:26.039 11686 16843 E ZomXMPP : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
01-28 11:14:26.039 11686 16843 E ZomXMPP : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
01-28 11:14:26.039 11686 16843 E ZomXMPP : 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:245)
01-28 11:14:26.039 11686 16843 E ZomXMPP : 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
01-28 11:14:26.039 11686 16843 E ZomXMPP : 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
01-28 11:14:26.039 11686 16843 E ZomXMPP : 	at org.awesomeapp.messenger.plugin.xmpp.XmppConnection$UploaderManager.uploadFile(XmppConnection.java:5320)
01-28 11:14:26.039 11686 16843 E ZomXMPP : 	at org.awesomeapp.messenger.plugin.xmpp.XmppConnection$UploaderManager.doUpload(XmppConnection.java:5222)
01-28 11:14:26.039 11686 16843 E ZomXMPP : 	at org.awesomeapp.messenger.plugin.xmpp.XmppConnection.publishFile(XmppConnection.java:1892)
01-28 11:14:26.039 11686 16843 E ZomXMPP : 	at org.awesomeapp.messenger.service.adapters.ImConnectionAdapter.publishFile(ImConnectionAdapter.java:671)
01-28 11:14:26.039 11686 16843 E ZomXMPP : 	at org.awesomeapp.messenger.service.adapters.ChatSessionAdapter$1.run(ChatSessionAdapter.java:594)
```

I have debug logs turned on, but that is all I see.

From the server logs, I can see that prosody successfully hands out the upload slot to the client.

**Comment by iamironrabbit** [comment]
Seems the address you return doesn't include an explicit port, and we see it as -1. That is different from the default prosody behavior. Handling it now!
